Zenika/sensei

webpack.config.js

See #11. This was caused by a mistake made while upgrading to Reveal 4 in https://github.com/Zenika/sensei/commit/aacf1ed298f20cbfdfa403abf7efc0b12197c3fb.

🐛 fix decktape/reveal error when generating pdf for slides

---

src/loaders/revealjs-loader.js

By default Prismjs do not load all lang and for exemple highlighting not working for typescript.
This new import will load all lang present in prismjs module

:sparkles: add more lang on Prismjs highlight

---

.gitignore
src/slides/slides.css
src/slides/slides.html

After trying to use `sensei` on `Angular avancé` training, slides doesn't display well because of header and code block. So I add some ajustements and improvements to style and keep compatibility.
- Reduce header size and margin
- Add `display: block` on code block to reduce `line-height`
- Improve code block visibility
- Remove specific rule for whole-slide code block (not sure to understand goal of this rule ?)

💄 improve compatibility with material using previous theme

---

src/loaders/revealjs-loader.js

Some formations slides use markdown comment to add attributes on paragraph element.
This is a proposal to preserve the  syntax & compatibility 
Examples : 
```
```
```
```

✨ support reveal's element attribute syntax

---

src/slides/slides.css

Currently it's not distinct from 'em' elements
Without:
With:
Used to do something like that in the K8S training:

💄 Highlight external links

---

src/slides/slides.css

This way, the header is highlighted a bit more than just with the thin red line.
Before: ![image](https://user-images.githubusercontent.com/175128/94420476-80042c00-0184-11eb-93b2-b82f35875a0b.png)
After: ![image](https://user-images.githubusercontent.com/175128/94420556-9f02be00-0184-11eb-8f1d-11d810184a81.png)

💄 Highlight table headers with bold

---

src/slides/slides.css

Proposal for change copyright color in favor of a lighter gray to set a little less visible
**Previous:** 
**Proposal:**

💄 change copyright color for a lighter gray

---

bin/sensei.js
webpack.config.js

See #45 for context of how this was found and how it can be reproduced. Fixes #45.
This fixes Webpack module resolution configuration so that it works correctly in all sensei use cases.
If also improves error handling in the CLI. Errors thrown from the Webpack build or child processes are properly reported, and unhandled promise rejections trigger a non-zero exit code.

🐛 fix build error when using as dependency

---

src/labs/labs.css
src/labs/labs.js

Add a `span` with class "version" to the first `div` of the Labs handbook.
Add CSS style for this `span`.
Fixes #53

:sparkles: Add version information in Labs

---

src/index.html
src/index.js
src/labs/labs.js
src/slides/slides.js
src/title.js

Here is a proposal to update Slides, Labs & index with the training material title (rather than always using "Zenika Formation").
The Labs cover page also gets updated with the material title, rather than "{Titre de la Formation}".
Let me know what you think about this.

✨ display training title where relevant

---

src/slides/slides.js

When writing multiple `$` in the same line, the text in-between gets interpreted as Math formula.
This delimiter is too generic.
Configure math plugin to only use `\(...\)`.
Example:
Inline is interpreted: `echo "${MY_VAR} is ${VAR_STATE}"`
Block is OK:
```shell
echo "${MY_VAR} is ${VAR_STATE}"
```
"Old" framework:
Sensei:
With this ix:

change math delimiter for math plugin

---

bin/sensei.js

This is a more cross-platformy way to run decktape. Even better would have been to run decktape without spawning a process, directly through a JS API, but decktape does not have one.

🐛 fix pdf command on windows

---

bin/sensei.js
package-lock.json
package.json
run.sh
src/index.css
src/index.html
webpack.config.js

See https://s-dot-formation-deeplearning-tensorflow2-dot-zen-formations.appspot.com/ for example.
These links point to the PDFs that are currently deployed in Google Cloud Storage, not local ones.
I'm not sure this is the best way to do this. I don't really like that the links always point to GCS. Maybe the links could be given at build time instead? Not sure. What do you think?
UPDATED: rebased, simplify for local and remote. Result for training template: https://sensei-dot-zenika-formation-modele-dot-zen-formations.appspot.com/

✨ add links to pdfs on index page

---

README.md

Referring to https://github.com/Zenika/training-template/pull/144#issuecomment-811138339
This way, sensei is available as a CLI `sensei` whatever the "installation" mode (docker or npm).

Change instruction to have a uniform CLI use of sensei

---

src/labs/labs.css

This allow to set it as HTML attribute through markdown

Do not force table cells text alignment in labs.

---

bin/sensei.js

Fixes #94 
It's one minimal way to do it using yargs, but use a fixed config file. Sadly didn't find a way to use a default fallback for yargs `config()` (when using `parseFn`, it's not called if no `--config` is provided)

🚸 support config file

---

bin/webpack.config.js
src/slides/slides.js

Because of Zenika-Training/training-template#150

👽 support both 'ressources' and 'resources' folders for custom css

---

bin/sensei.js

Attempt to fix #131.
Disable the hot module replacement feature of webpack dev server, which does not seem to work in our case (maybe because of #125?). This makes dev server use its "classic" live reload feature (full page reload) instead, which works.

🚑 fix live reload

---

src/app/index.html
src/app/labs/labs.html
src/app/slides/slides.html
src/build/webpack.config.test.js

Title is now HTML-escaped before being interpolated into the `data-title` attribute in `labs.html`. Also HTML-escaped other interpolations, where relevant. See #138. Added a test to prove the fix.

🐛 fix compile error when html in title

---

src/app/slides/slides.css

When multiple pages in file, each slide is a 'section' under a 'section[class=stack]',
but when only one page, the slide is not under a 'section' and the CSS rule didn't handle this case
Ping @moreau-nicolas
Example https://github.com/Zenika/formation-craftsmanship-sensibilisation/blob/update-template/Slides/07_kata_pingpong.md?plain=1 (using `page-demo` as a workaround)

Fix 'page-tp' when solo page in file

---

README.md

See https://github.com/Zenika/sensei/issues/147#issuecomment-1091188979.

📝 document how to change SENSEI_PORT

---

src/build/loaders/revealjs-loader.js

Minimize impact of #145 on existing trainings.

🐛 dont generate header ids to avoid conflict with section ids

---

src/build/webpack.config.js

```shell
$ docker container run --pull always --rm --volume $(CURDIR):/$(TRAINING_NAME) --workdir /$(TRAINING_NAME) --cap-add=SYS_ADMIN zenika/sensei pdf
fatal: unsafe repository ('/training-terraform' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /training-terraform
```
Do not understand why this happen as the folder is owned by user `chrome` executing `git`. (Maybe an issue with the `cwd`?)
This problem only occurs for Apple M1 and the arm64 build of sensei.
https://zenika.slack.com/archives/C063LTVU7/p1655282726494619
Ping @bgauduch 
Built [`zenika/sensei:arm64`](https://hub.docker.com/layers/sensei/zenika/sensei/arm64/images/sha256-9cbde1b23b5d48dcd8f48ff50009912194d49f882a9ac7f5d0cdf53a9f4920ee?context=explore) with …

Workaround for git error 'unsafe repository'

---

example/Slides/chapter_1.md
src/build/loaders/revealjs-loader.js

Fixes issue #144
Replace both start and end tags
Result:

Replace 'script' tags after Markdown rendering

---

Dockerfile
src/build/webpack.config.js

FIX #176 
Allow any directory to have a different owner than the container's USER (chrome - 501). 
Git's behaviour has changed in v2.35.1. See [here](https://github.blog/2022-04-12-git-security-vulnerability-announced/).
The option had to be put on any user (system) otherwise it did not work - git knows why.
Setting this option globally for the chrome user only did not fix the issue.
The same behavior is encountered on various SO threads, so I guess the option is too fresh in git and might fail somehow when set for a user..
Setting this option on system (ie. any user) makes it behave as it should.
Had to set the folder to any (*) because the documentation example of the docker command set a non-consistant volume path.

FIX #176 - disable safe directory warning globally for git

---

Dockerfile
package-lock.json
package.json
src/build/loaders/revealjs-loader.js
src/cli/cli.js
src/pdf/pdf.js

Should fix all security issues (https://github.com/Zenika/sensei/security/dependabot)
Only problem was random issue when generating PDF.
Don't know why...
But switched labs and slides generation order and no more error.
```
Processing folder '/training-template' as 'training-template' using slide size 1420x800 and language 'en'
Generate pdf slides & labs
Build slides & labs
Files generated to dist folder
Loading page http://localhost:45095/slides.html ...
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/5/7    (58/58) ...    
Printed 58 slides
PDF slides generated
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:236
? new Error(`${response.errorText} at ${url}`)
^
Error: net::ERR_ABORTED at http://localhost:45095/labs.html
at navigate …
```

⬆️ Upgrade dependencies

---

README.md

Hi!
I did not find instructions on how to use `sensei` natively on Mac Arm to generate PDF, so I added some instructions that worked for me.

:memo: add instruction to use native sensei to generate pdf on Mac Arm {M1,M2}

---

README.md
src/build/webpack.config.js
src/cli/cli.js

This can help get hot reloading work when running sensei with a VM-backed Docker from a host file system folder. For example, when running sensei with Docker for Windows with the WSL2 back-end from a Windows file system folder (see #117) or when running sensei with Colima from a macOS file system folder (see https://github.com/lima-vm/lima/issues/615). The recommendation still is to work off the VM file system to get native file watching.

✨ add support for polling when watching file changes

---

.circleci/config.yml

This way we'll have history of built images.

👷 Add timestamp tag on docker image
