Zenika/sensei

README.md

📝 document alias to run slides

---

src/slides/slides.css

It is already used in kubernetes training : 
```
```

✨ add css to have custom text for labs slide

---

build.sh
pdf.sh
src/pdf/.dockerignore
src/pdf/Dockerfile
src/pdf/package.json
src/pdf/pdf.js

Hey 👋
I added a Docker image for PDF generation (based on https://github.com/Zenika/alpine-chrome 😎 )
I also added the automatic generation of the PDF directory if it does not exist. 
For Decktape, I made a PR to make it possible : https://github.com/astefanutti/decktape/pull/218

🐳  Add docker image for pdf generation

---

src/labs/labs.js

Extracted from #25. Thanks to @ebriand.

✨ support code syntax highlighting in lab

---

Makefile
src/pdf/Makefile

Hey 👋 
I added to build docker images 🐳

🐳 Add Makefiles for docker image build

---

README.md
src/pdf/package.json

Hey 👋
This little PR fixes #26 
Again thanks @chocho01 to have directed us to the solution 👏

🐛 fix slides pdf rendering size

---

src/loaders/revealjs-loader.js
src/loaders/slides-json-loader.js
src/slides/slides.css

A new proposal to replace #31.

💄 add slide numbers and copyright

---

src/loaders/revealjs-loader.js

Hey 👋 
With #34, slides number were displayed in the labs PDF. I added a small condition to prevent it.

🐛 remove slides number from labs

---

src/index.css
src/index.html
src/index.js
webpack.config.js

Hey 👋 
This PR fixes #37. 
It is only a simple landing page, others can now add more style to it 😄

✨ add index page

---

bin/sensei.js

Hey 👋
With #32, when launching sensei with docker, it was not possible to stop it with CTRL+C. This PR fixes that.
Fixes #38

🐳  fix CTRL+C behavior

---

src/labs/labs.css
src/slides/slides.css

Before: ![image](https://user-images.githubusercontent.com/175128/94838963-a04b1980-0416-11eb-8a5f-62034a89465a.png)
After: ![image](https://user-images.githubusercontent.com/175128/94839011-b527ad00-0416-11eb-98c0-3b5e29f40e47.png)

💄 Fix line wrapping in code blocks

---

Dockerfile
src/pdf/pdf.js

- Fix font (#36)
- Fix size (A4 instead of US Letter)
Before/after: ![image](https://user-images.githubusercontent.com/175128/96146343-7a3d7300-0f06-11eb-957c-384bb811c1c8.png)

🐛 fix labs pdf font and paper size

---

package-lock.json
package.json
src/loaders/revealjs-loader.js
webpack.config.js

Do not display copyright between each labs

🐛  remove footer (copyright + page number) in labs slides

---

package-lock.json
package.json
src/loaders/revealjs-loader.js

If we decide to keep behavior of [zenika/zenika-formation-framework](https://github.com/Zenika/zenika-formation-framework) on this.
See https://github.com/Zenika/sensei/issues/52#issuecomment-767461747

✨ Render Markdown inside HTML blocks

---

bin/sensei.js
src/slides/slides-pdf.css
src/slides/slides-pdf.js
webpack.config.js

Fixes #54
Drastically reduce PDF file size, e.g. with K8S user training:
file | type | size
--- | --- | --
Zenika-training-material-Slides.pdf | without fix | **55.4M**
Zenika-training-material-Slides.pdf | with fix | **6.2M**

Disable box-shadow for PDF export of slides

---

src/loaders/revealjs-loader.js

Cf. https://github.com/Zenika/training-template/pull/144#issuecomment-810299049

Fixes for `.element`

---

src/slides/slides.js

Backport from
Zenika/zenika-formation-framework#170

✨ Support left-right only presentation remotes

---

README.md
bin/sensei.js
package-lock.json
package.json
src/slides/slides.js
webpack.config.js

This makes sensei compatible with training material that have content-dense slides that would overflow with the default size.
TODO: docs, remove port option (move it to another PR)

✨ make slide size adjustable

---

.circleci/config.yml
package-lock.json
package.json
src/loaders/slides-json-loader.test.js
test.js
webpack.config.js
webpack.config.test.js

This adds a very basic test that compiles a training material with no content. Still better than no test at all!

✅ add compilation test

---

bin/sensei.js

Better for analysing failures of PDF generation

Redirect stderr of spawned decktape for slides PDF.

---

webpack.config.js

Enable syntax highlighting in labs

---

README.md
bin/sensei.js

Makes it possible to serve multiple materials at the same time.

✨ add port argument

---

README.md
bin/webpack.config.js
bin/webpack.config.test.js
src/labs/labs.js

Still fallback to 'CahierExercices'
Fixes #75

🌐 Use 'Workbook' instead of 'CahierExercices'

---

Dockerfile
bin/sensei.js

🔒️ Expose on localhost by default

---

bin/webpack.config.js
src/slides/slides.js

💄: Handle 'custom.css' in slides

---

bin/sensei.js

Config option

---

bin/sensei.js
bin/webpack.config.js
src/index.html
src/labs/labs.html
src/slides/slides.html

Add CLI option to change the language. Used in CSS to change typo rules for punctuation.
With #104, this setting can also be commited.

🌐 Allow to set HTML document language

---

src/pdf/package-lock.json
src/pdf/package.json

fix #119 
Use a newer version of puppeteer to can be used with Mac M1
Now I can generate pdf, But the slides isn't well formated.

⬆ bump puppeteer to 11.0 and decktape to 3.3

---

package.json

Same as start script but reruns the CLI when the CLI code, the webpack config, or the webpack loaders change.

🛠 add dev script

---

bin/sensei.js
bin/webpack.config.js
package-lock.json
package.json

Useful when working on sensei itself, to see what actually ends up in the bundle.

🛠 add webpack bundle analyzer

---

src/pdf/pdf.js

🐛 wait for all resources to be loaded for labs PDF generation

---

src/cli/cli.js

🐛 fix SENSEI_PORT support

---

Dockerfile

🚑 pin chrome to v89

---

.circleci/config.yml

https://circleci.com/developer/orbs/orb/circleci/docker doesn't handle buildx, so need to create a local job for that.

👷 Enable multi-platform build

---

README.md

Sensei is way past the time of test drives!

📝 update readme intro

---

.circleci/config.yml

Update orb 'circleci/docker' to be able to update DockerHub description

---

src/build/loaders/workbook-json-loader.test.js
src/build/loaders/workbook-toc-loader.test.js

Follow-up of #158 on new tests

✅ Use same test syntax for all loader tests

---

src/app/index.html

Add version in index page

---

package-lock.json

- new lockfileVersion 3
- update some node packages to 18 (e.g. @types/node)
- clean-up
Generated by deleting + `npm i --package-lock-only`
Didn't see any impact on sensei execution.

⬆️ Regenerate package-lock.json file

---

Dockerfile

Install npm packages as non-root user to avoid package's UID/GID

---

src/cli/cli.js

See #192.
@gmembre-zenika Tu peux tester ?

🔇 reduce logging in serve mode
